sudo: required
services:
     - docker

before_install:
      - docker build -t demo/multiclient -f ./client/Dockerfile.dev ./client

script:
      - docker run demo/multiclient npm test -- --coverage

after_success:
      - docker build -t demo/multi-client ./client
      - docker build -t demo/multi-nginx ./nginx
      - docker build -t demo/multi-server ./server
      - docker build -t demo/multi-worker ./worker

# log in to the Docker Cli
      - echo "DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-std.in

# Push the images to docker hub
      - docker push demo/multi-client
      - docker push demo/multi-nginx
      - docker push demo/multi-server
      - docker push demo/multi-worker

