sudo: required
services:
     - docker

before_install:
      - docker build -t demo/multiclient -f ./client/Dockerfile.dev ./client

script:
      - docker run -e CI=true demo/multiclient npm test -- --coverage

after_success:
      - docker build -t shunmugam379/multi-client ./client
      - docker build -t shunmugam379/multi-nginx ./nginx
      - docker build -t shunmugam379/multi-server ./server
      - docker build -t shunmugam379/multi-worker ./worker

# log in to the Docker Cli
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Push the build images to docker hub
      - docker push shunmugam379/multi-client
      - docker push shunmugam379/multi-nginx
      - docker push shunmugam379/multi-server
      - docker push shunmugam379/multi-worker

deploy:
      edge: true
      provider: elasticbeanstalk
      region: "us-east-2"
      app: "multi-docker"
      env: "MultiDocker-env"
      bucket_name: "elasticbeanstalk-us-east-2-815347944718"
      bucket_path: multidocker

      
      on:
        branch: master
      access_key_id: $AWS_ACCESS_KEY
      secret_access_key: $AWS_SECRET_KEY
